### ISSUE TITLE
.NET Core version

### ISSUE THREAD

**Issue by ngbrown** [philiplaureano/LinFu#33]
How likely is a .NET Core version?  Can the approach LinFu is taking to make dynamic proxies be reused with .NET Core's limited API?

**Comment by philiplaureano** [comment]
@ngbrown I know it's two years late, but do you still need LinFu just for dynamic proxies? It should be easy to port the Dynamic Proxy generator to .NET Standard 2.0, provided that it has support for System.Reflection.Emit.

**Comment by ngbrown** [comment]
Closing as obsolete.
